name: Code Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: "1.26.0"

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ github.actor == 'dependabot[bot]' && github.token || secrets.CODE_QUALITY_ACCESS_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Format code
      run: make fmt

    - name: Commit format changes
      if: github.actor != 'dependabot[bot]'
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: 'fmt: format code'
        commit_author: 'GitHub Action <actions@github.com>'
        commit_user_email: 'action@github.com'

  vet:
    needs: format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - with:
        token: ${{ github.actor == 'dependabot[bot]' && github.token || secrets.CODE_QUALITY_ACCESS_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Lint code
      run: make vet

    - name: Commit format changes
      if: github.actor != 'dependabot[bot]'
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: 'vet: lint code'
        commit_author: 'GitHub Action <actions@github.com>'
        commit_user_email: 'action@github.com'

  test:
    needs: vet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ github.actor == 'dependabot[bot]' && github.token || secrets.CODE_QUALITY_ACCESS_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Copy .env
      run: cp .env.example .env || true

    - name: Run
      run: make run &

    - name: Wait for application to be ready
      run: |
        timeout 60 bash -c 'until curl -s http://localhost:8080 > /dev/null; do sleep 2; done'

    - name: Checkout code Expense Management Test
      uses: actions/checkout@v5
      with:
        repository: ajaycalicut17/expense-management-test
        path: expense-management-test

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      working-directory: expense-management-test
      run: npm ci

    - name: Install Playwright Browsers
      working-directory: expense-management-test
      run: npx playwright install --with-deps

    - name: Create .auth directory
      working-directory: expense-management-test
      run: mkdir -p .auth

    - name: Run Playwright tests
      working-directory: expense-management-test
      env:
        BASE_URL: http://localhost:8080
      run: npx playwright test -g "health"

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
